- hosts: all
  user: root

  tasks:

  - yum: 
      update_cache: yes

  - yum: 
      name: "chrony"

  - yum: 
      name: "nginx"

  - yum: 
      name: "git"
  
  - copy:
      src: template.nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - file: 
      path: /var/www/ansible-site
      state: directory
  
  - git: 
      repo: https://github.com/catalab/ansible-tut
      dest: /root/ansible-tutorial
      depth: 1

  - shell: rsync -ru --del /root/ansible-tutorial/www/ /var/www/ansible/

  - service:
      name: nginx
      state: restarted
      enabled: yes

